# Site settings
title: 'uMinded's blog'
description: 'uMinded's notes and projects'
url: 'https://iceblu3710.github.io/'
baseurl: '/'
# google_analytics: 'UA-75012409-1'
# disqus_shortname: 'iceblu3710githubio.disqus.com'

author:
  name: 'uMinded'
  email: iceblu3710@gmail.com
  github_username:  iceblu3710

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 5
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
